In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

c:\users\21053012\appdata\local\programs\python\python38\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\users\21053012\appdata\local\programs\python\python38\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
c:\users\21053012\appdata\local\programs\python\python38\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


pygame 2.3.0 (SDL 2.24.2, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'F:\Drowsiness-Detection--main\models\model.h5')

In [7]:
import cv2
import os
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import time


mixer.init()
sound = mixer.Sound('alarm.mp3')

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")
model = load_model(os.path.join("models", "model.h5"))


lbl=['Close', 'Open']

path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score = 0

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray,minNeighbors = 3,scaleFactor = 1.1,minSize=(25,25))
    eyes = eye_cascade.detectMultiScale(gray,minNeighbors = 1,scaleFactor = 1.1)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (255,0,0) , 3 )

    for (x,y,w,h) in eyes:

        eye = frame[y:y+h,x:x+w]
        #eye = cv2.cvtColor(eye,cv2.COLOR_BGR2GRAY)
        eye = cv2.resize(eye,(80,80))
        eye = eye/255
        eye = eye.reshape(80,80,3)
        eye = np.expand_dims(eye,axis=0)
        prediction = model.predict(eye)
        print(prediction)
       #Condition for Close
        if prediction[0][0]>0.30:
            cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            score=score+1
            #print("Close Eyes")
            if(score > 20):
                try:
                    sound.play()
                except:  # isplaying = False
                    pass

        #Condition for Open
        elif prediction[0][1] > 0.70:
            score = score - 1
            if (score < 0):
                score = 0
            cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            #print("Open Eyes")
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)

    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[1.4369563e-06 9.9999857e-01]]
[[0.0041725 0.9958275]]
[[0.00129256 0.9987074 ]]
[[8.089153e-06 9.999919e-01]]
[[5.2259004e-08 1.0000000e+00]]
[[0.0025674  0.99743265]]
[[0.86007994 0.13992012]]
[[5.3487275e-07 9.9999952e-01]]
[[0.00104012 0.9989599 ]]
[[8.263136e-06 9.999918e-01]]
[[0.00567404 0.99432594]]
[[7.94346e-06 9.99992e-01]]
[[0.0298842  0.97011584]]
[[1.1152144e-08 1.0000000e+00]]
[[0.00162645 0.9983735 ]]
[[4.466302e-08 1.000000e+00]]
[[0.00128547 0.99871457]]
[[9.480635e-05 9.999052e-01]]
[[0.04074099 0.95925903]]
[[2.9874422e-05 9.9997008e-01]]
[[0.00505578 0.9949443 ]]
[[1.9568969e-07 9.9999976e-01]]
[[0.001612   0.99838805]]
[[9.5108526e-06 9.9999046e-01]]
[[0.00246291 0.99753714]]
[[1.544859e-04 9.998455e-01]]
[[0.15271322 0.8472867 ]]
[[0.00216735 0.9978326 ]]
[[0.03550695 0.96449304]]
[[1.4807699e-06 9.9999857e-01]]
[[0.00750704 0.992493  ]]
[[9.9946207e-01 5.3789892e-04]]
[[0.90051943 0.09948058]]
[[9.9994349e-01 5.6524987e-05]]
[[0.98719317 0.01280678]]
[[0.648168